config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      post '/maps', to: 'maps#create'
    end
  end

  root 'welcome#index'

  get '/auth/google_oauth2', as: :google_oauth2_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get :logout, to: 'sessions#destroy'
  get '/cart', to: 'cart#show'
  resources :maps, only: [:new]
  resources :purchases, only: [:create, :show]
  resources :orders, only: [:new]
  resources :cart, only: [:create]
  match "*path", to: "application#error_404", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
  end

  def add_product(id)
    if contents.empty? || contents[id.to_s].nil?
      contents[id.to_s] = 1
    else
      contents[id.to_s] += 1
    end
  end

  def total_price
    contents.map do |product_id, quantity|
      Product.find(product_id).price * quantity
    end.sum
  end
end

app/models/map.rb
class Map < ApplicationRecord
  validates_presence_of :lat, :lng, :zoom

  def create_static(lat = self['lat'], lng = self['lng'], zoom = self['zoom'])
    self.assign_attributes(
      static_url: "http://maps.googleapis.com/maps/api/staticmap?&center=#{lat},#{lng}&zoom=#{zoom}&size=750x450&key=AIzaSyCJwmkCQw56cvtU03ftjoN1SpzL1VmTov4&style=feature:administrative|element:all|saturation:-100&style=feature:administrative.province|element:all|visibility:off&style=feature:landscape|element:all|saturation:-100|lightness:65|visibility:on&style=feature:poi|element:all|visibility:off&style=feature:road|element:all|saturation:-100&style=feature:road.highway|element:all|visibility:simplified&style=feature:road.arterial|element:all|lightness:30&style=feature:road.local|element:all|lightness:40&style=feature:transit|element:all|saturation:-100|visibility:simplified&style=feature:water|element:geometry|hue:0xffff00|lightness:-25|saturation:-97&style=feature:water|element:labels|lightness:-25|saturation:-100"
    )
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :description, :price
  validates_uniqueness_of :name

  has_many :product_orders
  has_many :orders, through: :product_orders
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  validates_presence_of :user_id
  has_many :purchase_products, dependent: :destroy
  belongs_to :user

  def total_price
    purchase_products.map do |purchase_product|
      purchase_product.product.price * purchase_product.quantity
    end.sum
  end
end

app/models/purchase_product.rb
class PurchaseProduct < ApplicationRecord
  validates_presence_of :quantity, :sale_price
  belongs_to :purchase
  belongs_to :product

  def subtotal
    product.price * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :email, :google_auth_token
  validates_uniqueness_of :email

  def self.update_or_create(auth)
    user = User.find_by(email: auth['info']['email']) || User.new
    user.attributes = {
      name: auth['info']['first_name'] + ' ' + auth['info']['last_name'],
      email: auth['info']['email'],
      google_auth_token: auth['credentials']['token']
    }
    user.save!
    user
  end
end

app/controllers/api/v1/maps_controller.rb
class Api::V1::MapsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    session[:map] = map_params
    # @current_map = current_map
    # @current_map.assign_attributes(map_params)
    # @current_map.create_static
    render js: "window.location = '#{new_order_path}'"
  end

  def show

  end

  private

  def map_params
    params.permit(:lat, :lng, :zoom)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_map
  before_action :current_map, :set_cart

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end

  def current_map
    @current_map ||= Map.new(session[:map])
  end

  def set_cart
    @cart ||= Cart.new(session[:cart])
  end

  def error_404
    render file: '/public/404', status: 404
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @coin_presenter = CoinPricePresenter.new
    @products = Product.where(id: @cart.contents.keys)
    @current_map = current_map
    @current_map.create_static
  end

  def create
    product = Product.find(params[:product_id])

    @cart.add_product(product.id)
    session[:cart] = @cart.contents
    redirect_to cart_path
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def new

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @current_map = current_map
    @current_map.create_static
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def show
    @purchase = Purchase.find(params[:id])
    @map = Map.find(@purchase.purchase_products[0].map_id)
  end

  def create
    quantity = @cart.contents.values[0]
    product_id = @cart.contents.keys[0]
    price = Product.find(product_id).price
    @purchase = Purchase.new(
      user_id: current_user.id
    )
    charge_error = nil
    begin
      customer = Stripe::Customer.create(
        :email => 'example@stripe.com',
        :card  => params[:stripeToken])

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => (params[:cost].to_f * 100).floor,
        :description => 'Rails Stripe customer',
        :currency    => 'usd')

    rescue Stripe::CardError => e
      charge_error = e.message
    end
    if charge_error
      flash[:error] = charge_error
      render :new
    else
      @current_map.create_static
      @current_map.save
      @purchase.save
      PurchaseProduct.create(
        quantity: quantity,
        sale_price: price,
        map_id: @current_map.id,
        purchase_id: @purchase.id,
        product_id: product_id
      )
      PurchaseConfirmationMailer.purchase_mailer(current_user).deliver_now
      session.delete(:cart)
      redirect_to purchase_path(@purchase)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.update_or_create(request.env['omniauth.auth'])
    session[:id] = user.id
    redirect_to '/'
  end

  def destroy
    reset_session
    redirect_to '/'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%B %d, %Y")
  end
end

app/views/cart/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-sm crypto-border">
        XRP price:
        <%= number_to_currency(@coin_presenter.ripple_price) %>
      </div>
      <div class="col-sm crypto-border">
        BTC price:
        <%= number_to_currency(@coin_presenter.bitcoin_price) %>
      </div>
      <div class="col-sm crypto-border">
        XLM price:
        <%= number_to_currency(@coin_presenter.stellar_price) %>
      </div>
      <div class="col-sm crypto-border">
        ETH price:
        <%= number_to_currency(@coin_presenter.ethereum_price) %>
      </div>
    </div>
  </div>
  <div class="mx-auto" style="width: 750px">

<% if @cart.contents.empty? %>
    <h3>There is nothing in your cart</h3>
<% else %>
  <h2>Your cart contains:</h2>

  <img class="map-image" src="<%= current_map['static_url'] %>" alt="">
  <div class="flag-image">
  <img src="<%= image_path('Colorado-Flag.jpg') %>" alt="" height="450px" width="750px">
  </div>
  <% @products.each do |product| %>
    <%= product.name %> <%= number_to_currency(product.price) %>
  <% end %>
  <p>Total:
    <%= number_to_currency(@cart.total_price) %></p>
  <%= form_tag purchases_path do %>
  <%= hidden_field_tag "cost", @cart.total_price %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>" data-description="A Map Which Cannot Be Believed" data-amount="<%= @cart.total_price * 100 %>" data-locale="auto"></script>

  <% end %>

<% end %>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <a href="/"><img class="logo-image" src="<%= image_path('flaglogo.png') %>" alt=""></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/maps/new">Create a Map</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/orders/new">Orders</a>
      </li>
    <li>

      </li>
      <% if current_user %>
        <li class="nav-item dropdown mr-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.name %></a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            <a class="dropdown-item" href="/orders/<%= current_user.id %>">Your Orders</a>
            <a class="dropdown-item" href="#">Saved Maps</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Settings</a>
            <a class="dropdown-item" href="/logout">Log Out</a>
          </div>
        </li>
      <% else %>
          <%= link_to "Log In", google_oauth2_login_path %>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoudSpeaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
  #map {
    height: 450px;
    width: 750px;
  }
</style>
  </head>

  <body>
    <%= render partial: '/layouts/nav_bar'%>
    <%= yield %>
  </body>
</html>

app/views/maps/new.html.erb
<div class="mx-auto" style="width: 750px">
  <div class="center">
    <div class="input-group mb-3">
      <input id="address" type="text" class="form-control" placeholder="Enter Your City" onkeypress="if(event.keyCode==13)codeAddress()" aria-label="Enter Your City" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <input type="button" value="Locate" onclick="codeAddress()" class="btn btn-outline-secondary">
      </div>
    </div>

    <button id="sendMapDataButton" onclick="sendMapData()" class="btn btn-primary btn-lg">Use This Map</button>
  </div>
  <div class="flex-container">
    <div id="map"></div>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAPS_API'] %>&callback=initMap" async="async" defer="defer"></script>
  </div>
</div>

app/views/orders/new.html.erb
<div class="mx-auto" style="width: 750px">
  <div class="center">
    <h3>Your map will look like this!</h3>
    <div class="flex-container">
      <div>
        <% if current_map %>
          <%= button_to 'Order This', cart_path(product_id: 1), :class => "btn btn-primary btn-lg" %>
          <img class="map-image" src="<%= current_map['static_url'] %>" alt="">
          <div class="flag-image">
            <img src="<%= image_path('Colorado-Flag.jpg') %>" alt="" height="450px" width="750px">
          </div>
        <% else %>
          <h2>You've got to pick a map first!</h2>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/purchases/show.html.erb
<div class="mx-auto" style="width: 750px">
  <div class="center">
    <% render file: 'public/404' if current_user.nil? || current_user.id == @purchase.user_id %>
      <h1><%= current_user['name'] %></h1>
      <h2>Your order from
        <%= format_date(@purchase.created_at) %></h2>
      <h2><%= number_to_currency(@purchase.total_price) %></h2>
      <img class="map-image" src="<%= @map.static_url %>" alt="">
      <div class="flag-image">
        <img src="<%= image_path('Colorado-Flag.jpg') %>" alt="" height="450px" width="750px">
      </div>
    </div>
  </div>

app/views/welcome/index.html.erb
<section class="vertical-center" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mx-auto text-center">
            <h2 class="section-heading text-white">Custom Laser Cut Maps!</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4"></p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="<%= new_map_path %>">Make it your own!</a>
          </div>
        </div>
      </div>
    </section>
<% cache 'a_word' do %>
<section>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="<%= image_path('map-side-angle.jpg') %>" alt="Map of Denver viewed from the side">
          <div class="carousel-caption">
            <h3>Intricate detail</h3>
          </div>
        </div>

        <div class="item">
          <img src="<%= image_path('map-overhead-angle.jpg') %>" alt="Map of Denver viewed from overhead">
          <div class="carousel-caption">
            <h3>Pick the exact size and location of the map you'd like</h3>
          </div>
        </div>

        <div class="item">
          <img src="<%= image_path('map-c-focused.jpg') %>" alt="Map of Denver focused on the Colorado Flag Center C">
          <div class="carousel-caption">
            <h3>Includes natural and man-made terrain</h3>
          </div>
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</section>
<% end %>